apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/taha-salam/wordpress-cicd-project.git
    targetRevision: main
    path: deploy/production
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
