apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/taha-salam/wordpress-cicd-project.git
    targetRevision: main
    path: deploy/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
